import { Document, Font, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import type { AnalysisResult } from '@/app/store';

// Use built-in Helvetica — no font download needed
Font.registerHyphenationCallback(word => [word]);

const COLORS = {
  bg: '#ffffff',
  text: '#0f172a',
  muted: '#64748b',
  border: '#e2e8f0',
  green: '#16a34a',
  yellow: '#ca8a04',
  red: '#dc2626',
  blue: '#2563eb',
  scoreHigh: '#16a34a',
  scoreMid: '#ca8a04',
  scoreLow: '#dc2626',
  accent: '#6366f1',
};

const s = StyleSheet.create({
  page: { backgroundColor: COLORS.bg, padding: 40, fontFamily: 'Helvetica', fontSize: 9 },
  // Header
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    paddingBottom: 14,
  },
  headerTitle: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: COLORS.text, marginBottom: 2 },
  headerMeta: { fontSize: 8, color: COLORS.muted },
  // Score row
  scoreRow: { flexDirection: 'row', gap: 10, marginBottom: 18 },
  scoreBox: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 6,
    padding: 12,
    alignItems: 'center',
  },
  scoreNum: { fontSize: 28, fontFamily: 'Helvetica-Bold', marginBottom: 2 },
  scoreLabel: { fontSize: 7, color: COLORS.muted, textTransform: 'uppercase', letterSpacing: 0.5 },
  catRow: { flex: 2, borderWidth: 1, borderColor: COLORS.border, borderRadius: 6, padding: 12 },
  catTitle: {
    fontSize: 7,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  catGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  catItem: { width: '30%' },
  catName: { fontSize: 7, color: COLORS.muted, marginBottom: 1 },
  catBar: { height: 3, backgroundColor: COLORS.border, borderRadius: 2, marginBottom: 1 },
  catFill: { height: 3, borderRadius: 2 },
  catScore: { fontSize: 7, color: COLORS.text },
  // Section
  section: { marginBottom: 14 },
  sectionTitle: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
    paddingBottom: 3,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  paragraph: { color: COLORS.text, lineHeight: 1.5, marginBottom: 4 },
  // Lists
  bullet: { flexDirection: 'row', marginBottom: 3 },
  bulletDot: { width: 12, color: COLORS.muted },
  bulletText: { flex: 1, color: COLORS.text, lineHeight: 1.4 },
  // Skill gaps
  gapRow: { flexDirection: 'row', marginBottom: 4, alignItems: 'flex-start' },
  gapDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6, marginTop: 1 },
  gapContent: { flex: 1 },
  gapSkill: { fontFamily: 'Helvetica-Bold', color: COLORS.text, marginBottom: 1 },
  gapContext: { color: COLORS.muted, lineHeight: 1.3 },
  gapPriority: { fontSize: 7, color: COLORS.muted },
  // Keywords
  kwRow: { flexDirection: 'row', gap: 10 },
  kwCol: { flex: 1 },
  kwColTitle: { fontSize: 7, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  kwChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 3 },
  kwChip: {
    borderWidth: 1,
    borderRadius: 3,
    paddingHorizontal: 4,
    paddingVertical: 1,
    fontSize: 7,
  },
  // Red flags
  flagRow: {
    flexDirection: 'row',
    marginBottom: 4,
    padding: 6,
    backgroundColor: '#fef2f2',
    borderRadius: 4,
  },
  flagText: { flex: 1, color: COLORS.red, lineHeight: 1.3 },
  // Footer
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: { fontSize: 7, color: COLORS.muted },
});

function scoreColor(n: number) {
  return n >= 70 ? COLORS.scoreHigh : n >= 50 ? COLORS.scoreMid : COLORS.scoreLow;
}

function priorityColor(p: string) {
  return p === 'critical' ? COLORS.red : p === 'important' ? COLORS.yellow : COLORS.green;
}

function catLabel(key: string) {
  const map: Record<string, string> = {
    technicalSkills: 'Technical',
    experience: 'Experience',
    cultureFit: 'Culture',
    keywords: 'Keywords',
    seniority: 'Seniority',
    tools: 'Tools',
  };
  return map[key] ?? key;
}

interface Props {
  result: AnalysisResult;
  company: string;
}

export function AnalysisPdfDocument({ result, company }: Props) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <Document title={`Analysis — ${company}`} author="AI Job Analyzer">
      <Page size="A4" style={s.page}>
        {/* ── Header ── */}
        <View style={s.header}>
          <Text style={s.headerTitle}>{company || 'Job Application Analysis'}</Text>
          <Text style={s.headerMeta}>Generated by AI Job Analyzer · {date}</Text>
        </View>

        {/* ── Score + Category grid ── */}
        <View style={s.scoreRow}>
          <View style={s.scoreBox}>
            <Text style={[s.scoreNum, { color: scoreColor(result.matchScore) }]}>
              {result.matchScore}%
            </Text>
            <Text style={s.scoreLabel}>Match Score</Text>
            <Text style={[s.scoreLabel, { marginTop: 2 }]}>{result.confidence} confidence</Text>
          </View>

          <View style={s.catRow}>
            <Text style={s.catTitle}>Category Scores</Text>
            <View style={s.catGrid}>
              {Object.entries(result.categoryScores).map(([key, val]) => (
                <View key={key} style={s.catItem}>
                  <Text style={s.catName}>{catLabel(key)}</Text>
                  <View style={s.catBar}>
                    <View
                      style={[s.catFill, { width: `${val}%`, backgroundColor: scoreColor(val) }]}
                    />
                  </View>
                  <Text style={s.catScore}>{val}%</Text>
                </View>
              ))}
            </View>
          </View>
        </View>

        {/* ── Summary ── */}
        <View style={s.section}>
          <Text style={s.sectionTitle}>Summary</Text>
          <Text style={s.paragraph}>{result.summary}</Text>
        </View>

        {/* ── Strengths ── */}
        {result.strengths.length > 0 && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Strengths</Text>
            {result.strengths.map((str, i) => (
              <View key={i} style={s.bullet}>
                <Text style={s.bulletDot}>•</Text>
                <Text style={s.bulletText}>{str}</Text>
              </View>
            ))}
          </View>
        )}

        {/* ── Skill Gaps ── */}
        {result.skillGaps.length > 0 && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Skill Gaps</Text>
            {result.skillGaps.map((gap, i) => (
              <View key={i} style={s.gapRow}>
                <View style={[s.gapDot, { backgroundColor: priorityColor(gap.priority) }]} />
                <View style={s.gapContent}>
                  <Text style={s.gapSkill}>
                    {gap.skill} <Text style={s.gapPriority}>({gap.priority})</Text>
                  </Text>
                  <Text style={s.gapContext}>{gap.context}</Text>
                </View>
              </View>
            ))}
          </View>
        )}

        {/* ── Recommendations ── */}
        {result.recommendations.length > 0 && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Recommendations</Text>
            {result.recommendations.map((rec, i) => (
              <View key={i} style={s.bullet}>
                <Text style={s.bulletDot}>{i + 1}.</Text>
                <Text style={s.bulletText}>{rec}</Text>
              </View>
            ))}
          </View>
        )}

        {/* ── Red Flags ── */}
        {result.redFlags.length > 0 && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Red Flags</Text>
            {result.redFlags.map((f, i) => (
              <View key={i} style={s.flagRow}>
                <Text style={s.flagText}>⚠ {f.flag}</Text>
              </View>
            ))}
          </View>
        )}

        {/* ── Keywords ── */}
        {(result.keywords.matched.length > 0 || result.keywords.missing.length > 0) && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>Keywords</Text>
            <View style={s.kwRow}>
              {result.keywords.matched.length > 0 && (
                <View style={s.kwCol}>
                  <Text style={[s.kwColTitle, { color: COLORS.green }]}>Matched</Text>
                  <View style={s.kwChips}>
                    {result.keywords.matched.map((kw, i) => (
                      <View key={i} style={[s.kwChip, { borderColor: COLORS.green }]}>
                        <Text style={{ color: COLORS.green }}>{kw}</Text>
                      </View>
                    ))}
                  </View>
                </View>
              )}
              {result.keywords.missing.length > 0 && (
                <View style={s.kwCol}>
                  <Text style={[s.kwColTitle, { color: COLORS.red }]}>Missing</Text>
                  <View style={s.kwChips}>
                    {result.keywords.missing.map((kw, i) => (
                      <View key={i} style={[s.kwChip, { borderColor: COLORS.red }]}>
                        <Text style={{ color: COLORS.red }}>{kw}</Text>
                      </View>
                    ))}
                  </View>
                </View>
              )}
            </View>
          </View>
        )}

        {/* ── ATS Score ── */}
        {result.atsScore && (
          <View style={s.section}>
            <Text style={s.sectionTitle}>ATS Score</Text>
            <Text style={s.paragraph}>
              Score: {result.atsScore.score}% · {result.atsScore.verdict.replace(/_/g, ' ')}
            </Text>
            {result.atsScore.missingKeywords.length > 0 && (
              <Text style={[s.paragraph, { color: COLORS.muted }]}>
                Missing ATS keywords: {result.atsScore.missingKeywords.join(', ')}
              </Text>
            )}
          </View>
        )}

        {/* ── Footer ── */}
        <View style={s.footer} fixed>
          <Text style={s.footerText}>AI Job Analyzer</Text>
          <Text
            style={s.footerText}
            render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}
